---
label: product
hide_body: true
fields:
- name: id
  type: text
  config:
    required: false
  label: id
  description: product id
- name: name
  type: text
  config:
    required: false
  label: name
  description: product name
- name: price
  type: number
  label: price
  default: 0
  required: true
  config:
    min: 0
    max: 
    step: 0.01
    required: true
  description: each price
- name: short_description
  type: text
  config:
    required: false
  label: short description
  description: product short description
- name: image
  type: file
  config:
    maxSize: 64
  label: image
  description: product image
- name: product_url
  type: text
  config:
    required: false
  label: product_url
  description: product url
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: description
  description: long description
pages:
- content/products/barn_owl.md
- content/products/barred_owl.md
- content/products/bigcheesewheel.md
